version: '3.9'

networks:
  exercise4:
    driver: bridge

volumes:
  psql-data:

services:
  postgres:
    container_name: local-psql
    image: postgres:16.2-alpine3.18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - "${PSQL_PORT}:5432"
    volumes:
      - ./config/psql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - psql-data:/var/lib/postgresql/data
    networks:
      - exercise4
